name: Build Gentoo Cache
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Run in chroot"
        if: ${{ github.event_name != 'pull_request' }}
        run: sudo -E ./scripts/create_chroot.sh
        env:
          TRAVIS_BRANCH: ${{ github.ref_name }}
          TRAVIS_PULL_REQUEST: false
